[tool.poetry]
name = "gest"
version = "0.1.0"
description = "Gesture recognition"
authors = ["Bartosz Marcinkowski <b.marcinkowski@leomail.pl>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.1"
numpy = "*"
onnxruntime = "^1.4.0"
opencv-python = "^4.4.0"
pynput = {version = "^1.6.8", optional = true }
pytorch-lightning = {version = "^0.9.0", optional = true }
torch = {version = "^1.6.0", optional = true }
torchvision = {version = "^0.7.0", optional = true }

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
training = [
    "pytorch-lightning",
    "torch",
    "torchvision",
]
examples = ["pynput"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
